# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\gabe\Desktop\thsr\TEST\thsr.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import time
import sys
#from keras.models import load_mode
from PyQt5.QtWidgets import QMessageBox
import requestBook
import threading

year, month, day, hour, min = map(int, time.strftime("%Y %m %d %H %M").split())

class Ui_Dialog(object):
    def __init__(self, model):
        self.model = model
    def setupUi(self, Dialog):
        Dialog.setObjectName("Just buy ticket")
        Dialog.resize(600, 546)
        self.selectStartStation = QtWidgets.QComboBox(Dialog)
        self.selectStartStation.setGeometry(QtCore.QRect(220, 90, 101, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.selectStartStation.setFont(font)
        self.selectStartStation.setObjectName("selectStartStation")
        self.selectStartStation.addItem("")
        self.selectStartStation.addItem("")
        self.selectStartStation.addItem("")
        self.selectStartStation.addItem("")
        self.selectStartStation.addItem("")
        self.selectStartStation.addItem("")
        self.selectStartStation.addItem("")
        self.selectStartStation.addItem("")
        self.selectStartStation.addItem("")
        self.selectStartStation.addItem("")
        self.selectStartStation.addItem("")
        self.selectStartStation.addItem("")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(110, 90, 101, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(110, 190, 101, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(110, 140, 101, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.F_ratio = QtWidgets.QRadioButton(Dialog)
        self.F_ratio.setGeometry(QtCore.QRect(110, 240, 98, 19))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.F_ratio.setFont(font)
        self.F_ratio.setObjectName("F_ratio")
        self.P_radio = QtWidgets.QRadioButton(Dialog)
        self.P_radio.setGeometry(QtCore.QRect(240, 240, 161, 19))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.P_radio.setFont(font)
        self.P_radio.setObjectName("P_radio")
        self.toTimeTable = QtWidgets.QComboBox(Dialog)
        self.toTimeTable.setGeometry(QtCore.QRect(360, 190, 80, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.toTimeTable.setFont(font)
        self.toTimeTable.setObjectName("toTimeTable")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.toTimeTable.addItem("")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(220, 290, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setText("S124852299")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(110, 290, 111, 16))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 340, 113, 22))
        self.lineEdit_2.setText("0966099087")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(110, 340, 111, 16))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.selectStartStation_2 = QtWidgets.QComboBox(Dialog)
        self.selectStartStation_2.setGeometry(QtCore.QRect(220, 140, 101, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.selectStartStation_2.setFont(font)
        self.selectStartStation_2.setObjectName("selectStartStation_2")
        self.selectStartStation_2.addItem("")
        self.selectStartStation_2.addItem("")
        self.selectStartStation_2.addItem("")
        self.selectStartStation_2.addItem("")
        self.selectStartStation_2.addItem("")
        self.selectStartStation_2.addItem("")
        self.selectStartStation_2.addItem("")
        self.selectStartStation_2.addItem("")
        self.selectStartStation_2.addItem("")
        self.selectStartStation_2.addItem("")
        self.selectStartStation_2.addItem("")
        self.selectStartStation_2.addItem("")
        self.dateEdit = QtWidgets.QDateEdit(Dialog)
        self.dateEdit.setGeometry(QtCore.QRect(220, 190, 110, 22))
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(year, month, day), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setObjectName("dateEdit")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(360, 160, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(230, 440, 93, 28))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.selectStartStation.setItemText(0, _translate("Dialog", "南港"))
        self.selectStartStation.setItemText(1, _translate("Dialog", "台北"))
        self.selectStartStation.setItemText(2, _translate("Dialog", "板橋"))
        self.selectStartStation.setItemText(3, _translate("Dialog", "桃園"))
        self.selectStartStation.setItemText(4, _translate("Dialog", "新竹"))
        self.selectStartStation.setItemText(5, _translate("Dialog", "苗栗"))
        self.selectStartStation.setItemText(6, _translate("Dialog", "台中"))
        self.selectStartStation.setItemText(7, _translate("Dialog", "彰化"))
        self.selectStartStation.setItemText(8, _translate("Dialog", "雲林"))
        self.selectStartStation.setItemText(9, _translate("Dialog", "嘉義"))
        self.selectStartStation.setItemText(10, _translate("Dialog", "台南"))
        self.selectStartStation.setItemText(11, _translate("Dialog", "左營"))
        self.selectStartStation.setCurrentIndex(3)
        self.label.setText(_translate("Dialog", "<html><head/><body><p>起站</p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">迄站</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">時間</span></p></body></html>"))
        self.F_ratio.setText(_translate("Dialog", "全票"))
        self.F_ratio.toggle()
        self.P_radio.setText(_translate("Dialog", "學生優惠票"))
        self.toTimeTable.setCurrentText(_translate("Dialog", "500A"))
        self.toTimeTable.setItemText(0, _translate("Dialog", "1201A"))
        self.toTimeTable.setItemText(1, _translate("Dialog", "1230A"))
        self.toTimeTable.setItemText(2, _translate("Dialog", "500A"))
        self.toTimeTable.setItemText(3, _translate("Dialog", "530A"))
        self.toTimeTable.setItemText(4, _translate("Dialog", "600A"))
        self.toTimeTable.setItemText(5, _translate("Dialog", "630A"))
        self.toTimeTable.setItemText(6, _translate("Dialog", "700A"))
        self.toTimeTable.setItemText(7, _translate("Dialog", "730A"))
        self.toTimeTable.setItemText(8, _translate("Dialog", "800A"))
        self.toTimeTable.setItemText(9, _translate("Dialog", "830A"))
        self.toTimeTable.setItemText(10, _translate("Dialog", "900A"))
        self.toTimeTable.setItemText(11, _translate("Dialog", "930A"))
        self.toTimeTable.setItemText(12, _translate("Dialog", "1000A"))
        self.toTimeTable.setItemText(13, _translate("Dialog", "1030A"))
        self.toTimeTable.setItemText(14, _translate("Dialog", "1100A"))
        self.toTimeTable.setItemText(15, _translate("Dialog", "1130A"))
        self.toTimeTable.setItemText(16, _translate("Dialog", "1200N"))
        self.toTimeTable.setItemText(17, _translate("Dialog", "1230P"))
        self.toTimeTable.setItemText(18, _translate("Dialog", "100P"))
        self.toTimeTable.setItemText(19, _translate("Dialog", "130P"))
        self.toTimeTable.setItemText(20, _translate("Dialog", "200P"))
        self.toTimeTable.setItemText(21, _translate("Dialog", "230P"))
        self.toTimeTable.setItemText(22, _translate("Dialog", "300P"))
        self.toTimeTable.setItemText(23, _translate("Dialog", "330P"))
        self.toTimeTable.setItemText(24, _translate("Dialog", "400P"))
        self.toTimeTable.setItemText(25, _translate("Dialog", "430P"))
        self.toTimeTable.setItemText(26, _translate("Dialog", "500P"))
        self.toTimeTable.setItemText(27, _translate("Dialog", "530P"))
        self.toTimeTable.setItemText(28, _translate("Dialog", "600P"))
        self.toTimeTable.setItemText(29, _translate("Dialog", "630P"))
        self.toTimeTable.setItemText(30, _translate("Dialog", "700P"))
        self.toTimeTable.setItemText(31, _translate("Dialog", "730P"))
        self.toTimeTable.setItemText(32, _translate("Dialog", "800P"))
        self.toTimeTable.setItemText(33, _translate("Dialog", "830P"))
        self.toTimeTable.setItemText(34, _translate("Dialog", "900P"))
        self.toTimeTable.setItemText(35, _translate("Dialog", "930P"))
        self.toTimeTable.setItemText(36, _translate("Dialog", "1000P"))
        self.toTimeTable.setItemText(37, _translate("Dialog", "1030P"))
        self.toTimeTable.setItemText(38, _translate("Dialog", "1100P"))
        self.toTimeTable.setItemText(39, _translate("Dialog", "1130P"))
        self.label_4.setText(_translate("Dialog", "身分證"))
        self.label_5.setText(_translate("Dialog", "手機"))
        self.selectStartStation_2.setItemText(0, _translate("Dialog", "南港"))
        self.selectStartStation_2.setItemText(1, _translate("Dialog", "台北"))
        self.selectStartStation_2.setItemText(2, _translate("Dialog", "板橋"))
        self.selectStartStation_2.setItemText(3, _translate("Dialog", "桃園"))
        self.selectStartStation_2.setItemText(4, _translate("Dialog", "新竹"))
        self.selectStartStation_2.setItemText(5, _translate("Dialog", "苗栗"))
        self.selectStartStation_2.setItemText(6, _translate("Dialog", "台中"))
        self.selectStartStation_2.setItemText(7, _translate("Dialog", "彰化"))
        self.selectStartStation_2.setItemText(8, _translate("Dialog", "雲林"))
        self.selectStartStation_2.setItemText(9, _translate("Dialog", "嘉義"))
        self.selectStartStation_2.setItemText(10, _translate("Dialog", "台南"))
        self.selectStartStation_2.setItemText(11, _translate("Dialog", "左營"))
        self.selectStartStation_2.setCurrentIndex(10)
        self.label_6.setText(_translate("Dialog", "5:00 AM = 500A"))
        self.pushButton.setText(_translate("Dialog", "送出"))
    
        self.pushButton.clicked.connect(self.click)
        
    def click(self):
        threads = []
        for i in range(5):
            threads.append(threading.Thread(target = self.send,args = (i,)))
            threads[i].start()

    
    def send(self, num):
        fall = '1F'
        student = '0P'        
        if self.P_radio.isChecked():
            fall = '0F'
            student = '1P'
        requestBook.book(self.model,
                         self.selectStartStation.currentIndex()+1,
                         self.selectStartStation_2.currentIndex()+1,
                         str(self.dateEdit.date().toPyDate()).replace('-', '/'),
                         self.toTimeTable.currentText(),
                         fall,
                         student,
                         self.lineEdit.text(),
                         self.lineEdit_2.text(),
                         num)

'''
if __name__ == '__main__':  
    
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Dialog()
    
    ui.setupUi(MainWindow) 
    MainWindow.show()
    msg = QMessageBox()
    sys.exit(app.exec_()) 
'''